name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH Key and Configure Known Hosts
        run: |
          # Ensure SSH directory exists
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Decode and write the private key to file
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Start SSH agent and add the private key
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

          # Add the AWS host to known hosts
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Log Environment Variables
        run: |
          # Log environment variables to check if they're set
          echo "AWS_HOST: ${{ secrets.AWS_HOST }}"
          echo "AWS_USERNAME: ${{ secrets.AWS_USERNAME }}"
          echo "DB_HOST: $DB_HOST"
          echo "DB_USER: $DB_USER"
          echo "DB_PASS: $DB_PASS"

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -v ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "echo 'SSH Connection Successful'"

      - name: Deploy Application to AWS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} << 'EOF'
            cd /home/ubuntu/app  # Change to your app directory
            git pull origin main  # Pull the latest code
            npm install           # Install dependencies
            pm2 restart all       # Restart the app with PM2
          EOF
