name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.AWS_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no "${{ secrets.AWS_USERNAME }}"@"${{ secrets.AWS_HOST }}" << 'EOF'
            # Navigate to app directory
            APP_DIR="/home/${{ secrets.AWS_USERNAME }}/app"
            mkdir -p ${APP_DIR}
            cd ${APP_DIR}

            # Clone or pull latest code
            if [ ! -d ".git" ]; then
              git clone https://github.com/SUNAY08/github-actions-demo.git .
            else
              git fetch origin
              git reset --hard origin/main
            fi

            # Install dependencies
            if ! command -v node &> /dev/null; then
              sudo apt update
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs
            fi

            npm install

            # Stop any existing node process and start new one
            pkill node || true
            nohup node app.js > app.log 2>&1 &
            echo "Server started successfully!"
          EOF